### PR TITLE
Fix/916 change default paths to parse victoire directory

### LINKED ISSUE #916: Error when trying to create or update a widget
## Description
In a project using victoire v2.3 (https://github.com/Victoire/victoire/commit/6bc46b6aa5b06aca76ea7f8ee86941e76c0582f0), when I try to create or update a widget, I get a critical error with the following message:
Undefined index: receiverProperty

## Resolution Ideas
After digging, the issue is related to the recents composer vendor paths changes of the widgets (from friendsofvictoire/my-widget to victoire/my-victoire).

Concerned files: 
- https://github.com/Victoire/victoire/blob/2.2/Bundle/BusinessEntityBundle/Reader/BusinessEntityCacheReader.php
- https://github.com/Victoire/victoire/blob/2.2/Bundle/BusinessEntityBundle/Annotation/AnnotationDriver.php
- https://github.com/Victoire/victoire/blob/2.2/Bundle/CoreBundle/DependencyInjection/Configuration.php#L45

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |  | Page           |  |
| Blog           |          | Query          |          |
| BusinessEntity | &#10004; |Seo             |          |
| BusinessPage   |          | Sitemap        |          |
| Core           | &#10004; | Template       |          |
| Criteria       |          | Twig           |          |
| Filter         |          | User           |          |
| Form           |          | ViewReference  |          |
| I18n           |          | Widget         |          |
| Media          |          | WidgetMap      |          |

### PR DESCRIPTION
**Pull request by lenybernard**
## Type
Bugfix

## Purpose
Fixes #916

## BC Break
YES

### CODE REVIEW

File: Bundle/BusinessEntityBundle/Annotation/AnnotationDriver.php [hunk 1]
```diff
@@ -88,7 +88,6 @@ public function getAllClassNames()
             );
             foreach ($iterator as $file) {
                 $sourceFile = realpath($file[0]);
-                require_once $sourceFile;
```
Comment (paulandrieux) [inline Bundle/BusinessEntityBundle/Annotation/AnnotationDriver.php]: Why remove this ? It was introduced in here: https://github.com/Victoire/victoire/commit/12739135d44cda681766c576c0a43989ed8cc212

Comment (paulandrieux) [inline Bundle/BusinessEntityBundle/Annotation/AnnotationDriver.php]: Doctrine does this "require_once" when the doctrine-bundle boots. If your cache:warmup works well even if you declare the DoctrineBundle under the BusinessEntityBundle in your AppKernel, then we can indeed remove this line.

File: Bundle/CoreBundle/DependencyInjection/Configuration.php [hunk 2]
```diff
@@ -43,7 +43,11 @@ public function getConfigTreeBuilder()
             ->end()
             ->children()
                 ->variableNode('base_paths')
-                    ->defaultValue(['%kernel.root_dir%/../src', '%kernel.root_dir%/../vendor/victoire/victoire/Bundle/BlogBundle', '%kernel.root_dir%/../vendor/friendsofvictoire'])
+                    ->defaultValue([
+                        '%kernel.root_dir%/../src',
+                        '%kernel.root_dir%/../vendor/victoire',
+                        '%kernel.root_dir%/../vendor/friendsofvictoire',
```
Comment (paulandrieux) [inline Bundle/CoreBundle/DependencyInjection/Configuration.php]: If cache:warmup breaks, it is always possible to support some "exclusion" in the "base_paths" like `!%kernel.root_dir%/../vendor/victoire/victoire/Tests`.
It would be necessary to support this exclusion in the annotationDriver:getAllClassNames() method
