### PR TITLE
1030 fix error with tests entities

### LINKED ISSUE #1030: Error with Victoire 2.3.28
## Description

I was able to upgrade Victoire in one of our projets, there is some warnings when running Composer:

```bash
$ composer require "symfony/symfony:~3.4.3" "victoire/victoire:~2.3.28"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                    
Nothing to install or update
Package symfony/swiftmailer-bridge is abandoned, you should avoid using it. No replacement was suggested.
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Widget name not found for widget Victoire\Widget\ForceBundle\Entity\WidgetForce. Is this widget declared in AppKernel ?
Widget name not found for widget Victoire\Widget\LightSaberBundle\Entity\WidgetLightSaber. Is this widget declared in AppKernel ?
```

It looks like it comes from https://github.com/Victoire/victoire/pull/1025/commits/e46c24b0b64eb931a8e5bebed86b211a9444b3ea.

And the website show a fatal exception:

> The class 'Acme\AppBundle\Entity\Jedi' was not found in the chain configured namespaces Gedmo\Loggable\Entity

## Resolution Ideas

- Move tests entities in a different directory?
- Load `Tests` entities only when testing Victoire

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |  | Page           |  |
| Blog           |          | Query          |          |
| BusinessEntity | &#10004;        |Seo             |          |
| BusinessPage   |          | Sitemap        |          |
| Core           |          | Template       |          |
| Criteria       |          | Twig           |          |
| Filter         |          | User           |          |
| Form           |          | ViewReference  |          |
| I18n           |          | Widget         |          |
| Media          |          | WidgetMap      |          |
| UI             |          |                |          |

### PR DESCRIPTION
**Pull request by alexislefebvre**
## Type
Bugfix: load tests entities only in the context of Victoire CI

## Purpose
Fixes #1030

## BC Break
NO

### CODE REVIEW

File: Bundle/CoreBundle/DependencyInjection/VictoireCoreExtension.php [hunk 1]
```diff
@@ -78,7 +78,7 @@ public function load(array $configs, ContainerBuilder $container)
             'victoire_core.base_paths', $config['base_paths']
         );
         $container->setParameter(
-            'victoire_core.base_paths', $config['base_paths']
```
Comment (alexislefebvre) [inline Bundle/CoreBundle/DependencyInjection/VictoireCoreExtension.php]: This line was a duplicate of the line 78.
